version: '3.4'

services:
  esettmvc:
    image: esettmvc
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "sa"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sqlvolume:/var/opt/mssql

volumes:
  sqlvolume:
